### ISSUE TITLE
Tolong ubah judul utama repository ini

### ISSUE THREAD

**Issue by playmakermz** [ramaiqbal/ramaiqbal.github.io#1]
- 'calculator.github.io' ubah menjadi 'ramaiqbal.github.io' 
- setelah itu tunggu beberapa menit dan cek pada 'settings'
  Pojok kiri bawah ( dibawah pilihan 'Secrets' ) check apakah muncul pilihan 'Pages'

**Comment by ramaiqbal** [comment]
siap kak

**Comment by ramaiqbal** [comment]
menunggu berapa menit saya
